name: Desplegar StaRelease en Firebase

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
    
    - name: 'Android autobump version'
      uses: 'MattiaFailla/android-version-autobump-action@main'
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       GRADLE_PATH: './app/build.gradle'
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name : Retrieve Version
      run: echo "VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_STATE
      id: android_version

    - name: Get version
      run: |
        echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV

    - name: Build with Gradle
      run: ./gradlew assembleRelease appDistributionUploadRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app
        path: app/businessSta/release/MoneyGO_${{env.version_name}}_business_release.apk
