name: Desplegar StaRelease en Firebase

on:
  workflow_dispatch:
  
  pull_request:
    types:
      - closed

jobs:

  if_major:
    if: ${{ github.event.pull_request.merged == true }} && ${{ github.event.label.name == 'major' }}
    uses: ./.github/workflows/MajorVersionNameBump.yml

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Bump version
      id: bump_version
      uses: oflynned/android-version-bump@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name : Retrieve Version
      run: echo "VERSION_NAME=$(${{github.workspace}}/gradlew -q printVersionName)" >> $GITHUB_STATE
      id: android_version

    - name: Get version
      run: |
        echo "version_name=${{steps.android_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV

    - name: Build with Gradle
      run: ./gradlew assembleRelease appDistributionUploadRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app
        path: app/businessSta/release/MoneyGO_${{env.version_name}}_business_release.apk
