name: Desplegar Release en Firebase

on:
  workflow_dispatch:
  
  pull_request:
    types:
      - closed

jobs:

  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    
    - name: if major
      if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'major')
      uses: ./.github/workflows/MajorVersionNameBump.yml
      
    - name: if minor
      if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'patch')
      uses: ./.github/workflows/PatchVersionNameBump.yml
      
    - name: if patch
      if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'patch')
      uses: ./.github/workflows/PatchVersionNameBump.yml

    - uses: actions/checkout@v3
    
    - name: Read value from Properties-file
      id: read_property
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: './version.properties'
        properties: majorVersion minorVersion patchVersion

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease appDistributionUploadRelease
      
    - name: Upload APK
      env:
        versionName: ${{ steps.read_property.outputs.majorVersion }}.${{ steps.read_property.outputs.minorVersion }}.${{ steps.read_property.outputs.patchVersion }}
        versionCode: $(($GITHUB_RUN_NUMBER+40)) 
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app
        path: app/build/outputs/apk/release/AppActions_release_${{ env.versionName }}_${{ env.versionCode }}.apk
