name: Desplegar Release en Firebase

on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - release/*

    types:
      - closed

jobs:

  if_major:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'major')
    uses: ./.github/workflows/MajorVersionNameBump.yml

  if_menor:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'minor')
    uses: ./.github/workflows/MinorVersionNameBump.yml

  if_patch:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'patch')
    uses: ./.github/workflows/PatchVersionNameBump.yml

  build:
    if: ${{ always() }}
    needs: [ if_major, if_menor, if_patch ]
    runs-on: ubuntu-latest

    steps:
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/keystore.jks

      - uses: actions/checkout@v3

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './version.properties'
          properties: majorVersion minorVersion patchVersion

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: calculate version code
        env:
          NUM: ${{ github.run_number }}
          SUM: $(($NUM+40))
        run: |
          echo "VERSION_CODE=${{ env.SUM }}" >> $GITHUB_ENV

      - name: Build with Gradle
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew bundleRelease appDistributionUploadRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.0
        with:
          name: Build Artifacts
          path: app/build/outputs/
