name: Desplegar StaRelease en Firebase

on:
  workflow_dispatch:
  
  pull_request:
    types:
      - closed

jobs:

  if_major:
    if: github.event.label.name == 'major'
    uses: ./.github/workflows/MajorVersionNameBump.yml

  if_menor:
    if: github.event.label.name == 'menor'
    uses: ./.github/workflows/MinorVersionNameBump.yml

  if_patch:
    if: github.event.label.name == 'patch'
    uses: ./.github/workflows/PatchVersionNameBump.yml

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    
    - name: Read value from Properties-file
      id: read_property
      uses: christian-draeger/read-properties@1.1.1
      with:
        path: './version.properties'
        properties: majorVersion minorVersion patchVersion

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease appDistributionUploadRelease
      
    - name: Upload APK
      env:
        versionName: ${{ steps.read_property.outputs.majorVersion }}.${{ steps.read_property.outputs.minorVersion }}.${{ steps.read_property.outputs.patchVersion }}
        versionCode: 60
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app
        path: app/release/AppActions_release_${{ env.versionName }}_${{ env.versionCode }}.apk
