name: Desplegar Release en Firebase

on:
  pull_request:
    branches: 
      - master
    types: [closed]
  workflow_dispatch:
    inputs:
      aab:
        type: boolean
        description: aab para playstore
        default: false

jobs:

  if_major:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'major')
    uses: ./.github/workflows/MajorVersionNameBump.yml

  if_menor:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'minor')
    uses: ./.github/workflows/MinorVersionNameBump.yml

  if_patch:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'patch')
    uses: ./.github/workflows/PatchVersionNameBump.yml

  build:
    if: ${{ always() }} && github.event.pull_request.merged == true
    needs: [ if_major, if_menor, if_patch ]
    runs-on: ubuntu-latest

    steps:
    
      - name: if aab
        shell: bash
        run: |
          if [ "${{ inputs.aab }}" == "" ]; then
            echo "AAB=true" >> $GITHUB_OUTPUT
          else
            echo "AAB=${{ inputs.aab }}" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v3
        with:
          ref: master

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          mkdir -p "./keystore"
          echo $ENCODED_STRING | base64 -d > "./keystore/keystore.jks"

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './version.properties'
          properties: majorVersion minorVersion patchVersion

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: calculate version code
        env:
          NUM: ${{ github.run_number }}
          SUM: $(($NUM+40))
        run: |
          echo "VERSION_CODE=${{ env.SUM }}" >> $GITHUB_ENV

      - name: Build with Gradle apk
        if: ${{ !env.AAB }}
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew assembleRelease
        
      - name: upload firebase apk
        if: ${{ !env.AAB }}
        uses: hasretsariyer/firebase-app-distribution-github-action@v1.0.0
        with:
          # Firebase App ID. You can find it in the Firebase console, on the General Settings page.
          app_id: "\"1:369609130996:android:564151c15b4d4d7f852fa1\""
          # Path of IPA or APK file to distribution.
          app_file: app/build/outputs/apk/release/AppActions_release_${{ env.versionName }}_${{ env.VERSION_CODE }}.apk
          # 'Firebase access token. You can create it by `firebase login:ci` on your local machine.
          # Visit [cli-ci-systems](https://firebase.google.com/docs/cli#cli-ci-systems) for more detail'
          firebase_token: "\"1//03XmL97L60uS1CgYIARAAGAMSNwF-L9IrXjGOk_TxI8sT7HoSFSsMi1sFQIz1zpLY1p8erBJiySnBqO20yG_Y-4HO1BJz86eKmjM\""
        # Distribution groups
        #  tester_groups: # optional
        # Release notes for this build.
        #  release_notes: # optional

      - name: Build with Gradle aab
        if: ${{ env.AAB }}
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.0
        env:
          versionName: ${{ steps.read_property.outputs.majorVersion }}.${{ steps.read_property.outputs.minorVersion }}.${{ steps.read_property.outputs.patchVersion }}
        with:
          name: AppActions_release_${{ env.versionName }}_${{ env.VERSION_CODE }}
          path: app/build/outputs/
