name: Desplegar StaRelease en Firebase

on:
  workflow_dispatch:
  
  pull_request:
    types:
      - closed

jobs:

  if_major:
    if: ${{ github.event.pull_request.merged == true }} && ${{ github.event.label.name == 'major' }}
    uses: ./.github/workflows/MajorVersionNameBump.yml

  if_menor:
    if: ${{ github.event.pull_request.merged == true }} && ${{ github.event.label.name == 'menor' }}
    uses: ./.github/workflows/MinorVersionNameBump.yml

  if_patch:
    if: ${{ github.event.pull_request.merged == true }} && ${{ github.event.label.name == 'patch' }}
    uses: ./.github/workflows/PatchVersionNameBump.yml

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease appDistributionUploadRelease
      
    - name: Upload APK
      uses: actions/upload-artifact@v3.1.0
      with:
        name: app
        path: app/businessSta/release/MoneyGO_${{env.version_name}}_business_release.apk
