name: VersionNameMajor Bump 

on: [workflow_dispatch]

env:
  MAJOR_VERSION: 0

jobs:
  builder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './version.properties'
          properties: majorVersion

      - name: bump version
        env:
          NUM: ${{ steps.read_property.outputs.majorVersion }}
        run: |
          echo $(( $NUM+1 )) >> $MAJOR_VERSION 
          echo $MAJOR_VERSION
        
      - name: Write value to Properties-file
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './version.properties'
          property: majorVersion
          value: "$MAJOR_VERSION"
            
            
      - name: commit properties file
        uses: EndBug/add-and-commit@v9
        with:
          add: './version.properties'
          message: "bump major version to $MAJOR_VERSION"
