name: Test secrets

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Write secrets
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './secrets.properties'
          property: |
            KEYSTORE_FILE
            KEYSTORE_PASSWORD
            SIGNING_KEY_ALIAS
            SIGNING_KEY_PASSWORD
          value: |
            ${{ secrets.KEYSTORE_FILE }}
            ${{ secrets.KEYSTORE_PASSWORD }}
            ${{ secrets.SIGNING_KEY_ALIAS }}
            ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './secrets.properties'
          properties: KEYSTORE_FILE KEYSTORE_PASSWORD SIGNING_KEY_ALIAS SIGNING_KEY_PASSWORD
