name: VersionNamePatch Bump 

on: [workflow_dispatch]

env:
  PATCH_VERSION: 0

jobs:
  builder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read value from Properties-file
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './version.properties'
          properties: majorVersion minorVersion patchVersion

      - name: bump patch version
        env:
          NUM: ${{ steps.read_property.outputs.patchVersion }}
          SUM: $(($NUM+1))
        run: |
          echo "PATCH_VERSION=${{ env.SUM }}"
          echo "PATCH_VERSION=${{ env.SUM }}" >> $GITHUB_ENV
          echo $PATCH_VERSION

      - name: Write patch version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: './version.properties'
          property:  patchVersion
          value: ${{ env.PATCH_VERSION }}

      - name: commit properties file
        uses: EndBug/add-and-commit@v9
        with:
          add: './version.properties'
          message: "bump patch version to ${{ steps.read_property.outputs.majorVersion }}.${{ steps.read_property.outputs.minorVersion }}.${{ env.PATCH_VERSION }}"
